### ISSUE TITLE
Can you provide local_manifests?

### ISSUE THREAD

**Issue by wjrlxa** [nofearnohappy/android_device_xiaomi_hermes#1]
Im using this device to compile CM12.1. But the errors in the process. 
Can you provide local_manifests?
Thank you~

**Comment by nofearnohappy** [comment]
. build/envsetup.sh && breakfast hermes
make otapackage -j8

**Comment by wjrlxa** [comment]
Thank you

**Comment by wjrlxa** [comment]
make completed successfully,but the phone can't boot up.
